import type { Metadata } from 'next';
import { Geist, Geist_Mono, ADLaM_Display } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const adLaMDisplay = ADLaM_Display({
  weight: '400',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  analytics,
  team,
}: Readonly<{
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adLaMDisplay.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto">
          <div className="flex justify-center gap-5 text-blue-500">
            <Link href={'/'}>Home</Link>
            <Link href={'/visitors'}>Visitors</Link>
          </div>
          <div className="flex justify-center gap-5">
            {team}
            {analytics}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
