import type { Metadata } from 'next';
import { Geist, Geist_Mono, ADLaM_Display } from 'next/font/google';
import './globals.css';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const adLaMDisplay = ADLaM_Display({
  weight: '400',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adLaMDisplay.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {modal}
      </body>
    </html>
  );
}
